import argparse

def parse_args(args=None):
    parser = argparse.ArgumentParser(description= "Cosmic Shield Simulator Optimizer")
    parser.add_argument("-mr", "--max-runs", type=int, help="Max number of simulations", default=1000)
    parser.add_argument("-sb", "--searchsp-builder", type=str, help="Search space builder class", default="searchsp_adv250814.SearchSpaceBuilderAdv250814")
    parser.add_argument("-of", "--objfun-evaluator", type=str, help="Object function evaluation class", default="objfun_base250801.ObjFEval_Base250801")
    parser.add_argument("-op", "--objfun-params", type=str, help="Object function evaluation parameters", default=None)
    parser.add_argument("-ta", "--target-evaluator", type=str, help="Target evaluator class", default="trgeval_base250801.TargetEval_Base250801")
    #parser.add_argument("-sb", "--searchsp-builder", type=str, help="Search space builder class", default="searchsp_default.SearchSpaceBuilderDef")
    #parser.add_argument("-ip", "--initial-points", type=int, help="Number of random initial points", default=200)
    parser.add_argument("-hf", "--history-file", type=str, help="Attempts history file path", default="./state/css_optimizer_state.pkl")
    #parser.add_argument("-hc", "--history-clip", type=int, help="Latest slice to consider, of the history", default=0)
    parser.add_argument("-hs", "--history-slice", type=str, help="History slicing directive ('a:b' -> from a-th element, length b, 'a:'  -> from a-th element to end, ':b'  -> first b elements, '-:b'  -> last b elements)", default=None)
    parser.add_argument("-ee", "--energy-efficiency", type=float, help="Target energy efficiency", default=0.9)
    parser.add_argument("-pe", "--protection-efficiency", type=float, help="Target protection efficiency", default=0.9)
    parser.add_argument("-pv", "--penalize-value", type=float, help="Value for penalization", default=1e6)
    parser.add_argument("-sc", "--sim-script", type=str, help="Simulator launch script path", default="./css_wrap.sh")
    parser.add_argument("-gd", "--geom-directory", type=str, help="Target directory for geometry configuration files", default="./config/optim")
    parser.add_argument("-gt", "--geom-template", type=str, help="Geometry configuration template path", default="./config/geometry_template.json")
    parser.add_argument("-lc", "--layer-config", type=str, help="Layer common configurations path", default="./config/layer_config.json")
    #parser.add_argument("-kf", "--kpis-file", type=str, help="KPIs file path", default="./global_kpis.csv")
    parser.add_argument("-or", "--outputdata-root", type=str, help="Output data root", default="./out")
    parser.add_argument("-md", "--materials-database", type=str, help="Materials database file", default=None)
    parser.add_argument("-ml", "--materials-list", type=str, help="Materials list file", default="./config/materials.txt")
    parser.add_argument("-lm", "--min-layers", type=int, help="Min number of layers", default=1)
    parser.add_argument("-lx", "--max-layers", type=int, help="Max number of layers", default=10)
    parser.add_argument("-tm", "--min-thickness", type=float, help="Min layer thickness (mm)", default=1.0)
    parser.add_argument("-tx", "--max-thickness", type=float, help="Max layer thickness (mm)", default=10.0)
    parser.add_argument("-nt", "--min-tot-thickness", type=float, help="Min total thickness (mm)", default=0.0)
    parser.add_argument("-mt", "--max-tot-thickness", type=float, help="Max total thickness (mm)", default=30.0)
    parser.add_argument("-sm", "--min-stiffness", type=float, help="Min total stiffness", default=0.0)
    parser.add_argument("-sx", "--max-stiffness", type=float, help="Max total stiffness", default=100.0)
    parser.add_argument("-mw", "--max-tot-weight", type=float, help="Max total weight (kg/m2)", default=20.0)
    parser.add_argument("-mc", "--max-tco", type=int, help="Max TCO (Total Cost of Ownership)", default=10)
    parser.add_argument("-x0", "--x0-file", type=str, help="Initial shield configuration", default=None)
    parser.add_argument("-xr", "--rnd-x0-fallback", action="store_true", help="if X0 could not be loaded in any way and this flag is set, a custom random X0 will be generated (instead of letting the gp_minimized do this for you. Additional details about why this could be best can be found in the readme)")
    parser.add_argument("-oc", "--optimizer-config", type=str, help="Core optimization engine configuration file", default="./config/optimizer_conf.json")
    parser.add_argument("-vo", "--verbose-optimization", action="store_true", help="Enable verbose optimization logging")
    parser.add_argument("-sf", "--stop-file", type=str, help="Stop file path", default=None)

    pArgs = parser.parse_args(args)
    return pArgs


